/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { QuizResult } from "./QuizResult";
import { QuizResultCountArgs } from "./QuizResultCountArgs";
import { QuizResultFindManyArgs } from "./QuizResultFindManyArgs";
import { QuizResultFindUniqueArgs } from "./QuizResultFindUniqueArgs";
import { DeleteQuizResultArgs } from "./DeleteQuizResultArgs";
import { QuizResultService } from "../quizResult.service";
@graphql.Resolver(() => QuizResult)
export class QuizResultResolverBase {
  constructor(protected readonly service: QuizResultService) {}

  async _quizResultsMeta(
    @graphql.Args() args: QuizResultCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [QuizResult])
  async quizResults(
    @graphql.Args() args: QuizResultFindManyArgs
  ): Promise<QuizResult[]> {
    return this.service.quizResults(args);
  }

  @graphql.Query(() => QuizResult, { nullable: true })
  async quizResult(
    @graphql.Args() args: QuizResultFindUniqueArgs
  ): Promise<QuizResult | null> {
    const result = await this.service.quizResult(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => QuizResult)
  async deleteQuizResult(
    @graphql.Args() args: DeleteQuizResultArgs
  ): Promise<QuizResult | null> {
    try {
      return await this.service.deleteQuizResult(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
