/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Certificate } from "./Certificate";
import { CertificateCountArgs } from "./CertificateCountArgs";
import { CertificateFindManyArgs } from "./CertificateFindManyArgs";
import { CertificateFindUniqueArgs } from "./CertificateFindUniqueArgs";
import { DeleteCertificateArgs } from "./DeleteCertificateArgs";
import { CertificateService } from "../certificate.service";
@graphql.Resolver(() => Certificate)
export class CertificateResolverBase {
  constructor(protected readonly service: CertificateService) {}

  async _certificatesMeta(
    @graphql.Args() args: CertificateCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Certificate])
  async certificates(
    @graphql.Args() args: CertificateFindManyArgs
  ): Promise<Certificate[]> {
    return this.service.certificates(args);
  }

  @graphql.Query(() => Certificate, { nullable: true })
  async certificate(
    @graphql.Args() args: CertificateFindUniqueArgs
  ): Promise<Certificate | null> {
    const result = await this.service.certificate(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Certificate)
  async deleteCertificate(
    @graphql.Args() args: DeleteCertificateArgs
  ): Promise<Certificate | null> {
    try {
      return await this.service.deleteCertificate(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
