/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { UserCertificate } from "./UserCertificate";
import { UserCertificateCountArgs } from "./UserCertificateCountArgs";
import { UserCertificateFindManyArgs } from "./UserCertificateFindManyArgs";
import { UserCertificateFindUniqueArgs } from "./UserCertificateFindUniqueArgs";
import { DeleteUserCertificateArgs } from "./DeleteUserCertificateArgs";
import { UserCertificateService } from "../userCertificate.service";
@graphql.Resolver(() => UserCertificate)
export class UserCertificateResolverBase {
  constructor(protected readonly service: UserCertificateService) {}

  async _userCertificatesMeta(
    @graphql.Args() args: UserCertificateCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [UserCertificate])
  async userCertificates(
    @graphql.Args() args: UserCertificateFindManyArgs
  ): Promise<UserCertificate[]> {
    return this.service.userCertificates(args);
  }

  @graphql.Query(() => UserCertificate, { nullable: true })
  async userCertificate(
    @graphql.Args() args: UserCertificateFindUniqueArgs
  ): Promise<UserCertificate | null> {
    const result = await this.service.userCertificate(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => UserCertificate)
  async deleteUserCertificate(
    @graphql.Args() args: DeleteUserCertificateArgs
  ): Promise<UserCertificate | null> {
    try {
      return await this.service.deleteUserCertificate(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
