/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { UserAffiliateClick } from "./UserAffiliateClick";
import { UserAffiliateClickCountArgs } from "./UserAffiliateClickCountArgs";
import { UserAffiliateClickFindManyArgs } from "./UserAffiliateClickFindManyArgs";
import { UserAffiliateClickFindUniqueArgs } from "./UserAffiliateClickFindUniqueArgs";
import { DeleteUserAffiliateClickArgs } from "./DeleteUserAffiliateClickArgs";
import { UserAffiliateClickService } from "../userAffiliateClick.service";
@graphql.Resolver(() => UserAffiliateClick)
export class UserAffiliateClickResolverBase {
  constructor(protected readonly service: UserAffiliateClickService) {}

  async _userAffiliateClicksMeta(
    @graphql.Args() args: UserAffiliateClickCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [UserAffiliateClick])
  async userAffiliateClicks(
    @graphql.Args() args: UserAffiliateClickFindManyArgs
  ): Promise<UserAffiliateClick[]> {
    return this.service.userAffiliateClicks(args);
  }

  @graphql.Query(() => UserAffiliateClick, { nullable: true })
  async userAffiliateClick(
    @graphql.Args() args: UserAffiliateClickFindUniqueArgs
  ): Promise<UserAffiliateClick | null> {
    const result = await this.service.userAffiliateClick(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => UserAffiliateClick)
  async deleteUserAffiliateClick(
    @graphql.Args() args: DeleteUserAffiliateClickArgs
  ): Promise<UserAffiliateClick | null> {
    try {
      return await this.service.deleteUserAffiliateClick(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
