/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { UserVideoPurchase } from "./UserVideoPurchase";
import { UserVideoPurchaseCountArgs } from "./UserVideoPurchaseCountArgs";
import { UserVideoPurchaseFindManyArgs } from "./UserVideoPurchaseFindManyArgs";
import { UserVideoPurchaseFindUniqueArgs } from "./UserVideoPurchaseFindUniqueArgs";
import { DeleteUserVideoPurchaseArgs } from "./DeleteUserVideoPurchaseArgs";
import { UserVideoPurchaseService } from "../userVideoPurchase.service";
@graphql.Resolver(() => UserVideoPurchase)
export class UserVideoPurchaseResolverBase {
  constructor(protected readonly service: UserVideoPurchaseService) {}

  async _userVideoPurchasesMeta(
    @graphql.Args() args: UserVideoPurchaseCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [UserVideoPurchase])
  async userVideoPurchases(
    @graphql.Args() args: UserVideoPurchaseFindManyArgs
  ): Promise<UserVideoPurchase[]> {
    return this.service.userVideoPurchases(args);
  }

  @graphql.Query(() => UserVideoPurchase, { nullable: true })
  async userVideoPurchase(
    @graphql.Args() args: UserVideoPurchaseFindUniqueArgs
  ): Promise<UserVideoPurchase | null> {
    const result = await this.service.userVideoPurchase(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => UserVideoPurchase)
  async deleteUserVideoPurchase(
    @graphql.Args() args: DeleteUserVideoPurchaseArgs
  ): Promise<UserVideoPurchase | null> {
    try {
      return await this.service.deleteUserVideoPurchase(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
