/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  UserVideoPurchase as PrismaUserVideoPurchase,
} from "@prisma/client";

export class UserVideoPurchaseServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.UserVideoPurchaseCountArgs, "select">
  ): Promise<number> {
    return this.prisma.userVideoPurchase.count(args);
  }

  async userVideoPurchases(
    args: Prisma.UserVideoPurchaseFindManyArgs
  ): Promise<PrismaUserVideoPurchase[]> {
    return this.prisma.userVideoPurchase.findMany(args);
  }
  async userVideoPurchase(
    args: Prisma.UserVideoPurchaseFindUniqueArgs
  ): Promise<PrismaUserVideoPurchase | null> {
    return this.prisma.userVideoPurchase.findUnique(args);
  }
  async createUserVideoPurchase(
    args: Prisma.UserVideoPurchaseCreateArgs
  ): Promise<PrismaUserVideoPurchase> {
    return this.prisma.userVideoPurchase.create(args);
  }
  async updateUserVideoPurchase(
    args: Prisma.UserVideoPurchaseUpdateArgs
  ): Promise<PrismaUserVideoPurchase> {
    return this.prisma.userVideoPurchase.update(args);
  }
  async deleteUserVideoPurchase(
    args: Prisma.UserVideoPurchaseDeleteArgs
  ): Promise<PrismaUserVideoPurchase> {
    return this.prisma.userVideoPurchase.delete(args);
  }
}
